language: node_js
cache:
  directories:
  - "$HOME/build/unfoldingWord-dev/node-gogs-client/node_modules"
sudo: false
node_js:
- '5.1'
before_script:
- npm install
- npm install gulp -g
script: gulp
before_install:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -K $encrypted_9c3492b4569b_key
  -iv $encrypted_9c3492b4569b_iv -in config.json.enc -out tests/config.json -d; fi
